# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  bulletml_config = debug
endif
ifeq ($(config),release)
  bulletml_config = release
endif

PROJECTS := bulletml

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

bulletml:
ifneq (,$(bulletml_config))
	@echo "==== Building bulletml ($(bulletml_config)) ===="
	@${MAKE} --no-print-directory -C . -f bulletml.make config=$(bulletml_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f bulletml.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   bulletml"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"