# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  libbulletml_config = debug
endif
ifeq ($(config),release)
  libbulletml_config = release
endif

PROJECTS := libbulletml

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

libbulletml:
ifneq (,$(libbulletml_config))
	@echo "==== Building libbulletml ($(libbulletml_config)) ===="
	@${MAKE} --no-print-directory -C . -f libbulletml.make config=$(libbulletml_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f libbulletml.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   libbulletml"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"